include("$(BOARD_DIR)/manifest.py")

module("microdot/microdot_asgi.py")
module("microdot/microdot_asgi_websocket.py")
module("microdot/microdot_asyncio.py")
module("microdot/microdot_asyncio_test_client.py")
module("microdot/microdot_asyncio_websocket.py")
module("microdot/microdot_cors.py")
module("microdot/microdot_jinja.py")
module("microdot/microdot.py")
module("microdot/microdot_session.py")
module("microdot/microdot_ssl.py")
module("microdot/microdot_test_client.py")
module("microdot/microdot_utemplate.py")
module("microdot/microdot_websocket_alt.py")
module("microdot/microdot_websocket.py")
module("microdot/microdot_wsgi.py")