include("$(BOARD_DIR)/manifest.py")

module("microdot_asgi.py", base_path = "microdot/")
module("microdot_asgi_websocket.py", base_path = "microdot/")
module("microdot_asyncio.py", base_path = "microdot/")
module("microdot_asyncio_test_client.py", base_path = "microdot/")
module("microdot_asyncio_websocket.py", base_path = "microdot/")
module("microdot_cors.py", base_path = "microdot/")
module("microdot_jinja.py", base_path = "microdot/")
module("microdot.py", base_path = "microdot/")
module("microdot_session.py", base_path = "microdot/")
module("microdot_ssl.py", base_path = "microdot/")
module("microdot_test_client.py", base_path = "microdot/")
module("microdot_utemplate.py", base_path = "microdot/")
module("microdot_websocket_alt.py", base_path = "microdot/")
module("microdot_websocket.py", base_path = "microdot/")
module("microdot_wsgi.py", base_path = "microdot/")